### ISSUE TITLE
关于格洛斯特数据集

### ISSUE THREAD

**Issue by QiaoFH** [yulisun/SRF#1]
您的论文《Structural Regression Fusion for Unsupervised Multimodal Change Detection》，其中提到了由Quickbird 2卫星和TerraSAR-X卫星采集的Gloucester数据集（原文中的dataset#6），您在github上的代码也包含了该数据集的mat格式的文件。文章中提到该数据集的大小是4135×2325，分辨率为0.65m，但是github里的mat格式文件大小为827×465，转换为png格式后放大看图像细节比较模糊，不太像是0.65m的分辨率。我也阅读了其他的相关的异质图像变化检测的论文，很多人也用了这个数据集，但是大多都没有标注数据集的来源，因此想向您请教一些该数据集的细节，您是否有该数据集的原始下载地址？github上面该数据集是经过重采样了吗？期待您的解答！

**Comment by yulisun** [comment]
您好，github上的数据是下采样过了的，原始4135×2325图像有80多M，不便于github上传。如果方便的话请邮件联系，我需要知道您使用这个数据集是用于研究或是其他用途。

**Comment by QiaoFH** [comment]
我向您github主页留的ustc邮箱发送了邮件但是被系统退信了。我是电子信息工程学院的在读硕士生，我的课题与异质图像变化检测相关，需要一些分辨率高的数据集进行研究。我查阅的相关数据集中只有具有0.65m分辨率的格洛斯特数据集比较契合要求，但是我并没有找到该数据集的下载地址。因此尝试向您咨询。我的电子邮箱地址是QiaoFH1120@126.com，期待您的回复！

**Comment by whw2021** [comment]
> 我向您github主页留的ustc邮箱发送了邮件但是被系统退信了。我是电子信息工程学院的在读硕士生，我的课题与异质图像变化检测相关，需要一些分辨率高的数据集进行研究。我查阅的相关数据集中只有具有0.65m分辨率的格洛斯特数据集比较契合要求，但是我并没有找到该数据集的下载地址。因此尝试向您咨询。我的电子邮箱地址是[QiaoFH1120@126.com](mailto:QiaoFH1120@126.com)，期待您的回复！

同学你好，我的方向也是异构图像变化检测，请问你现在有这个高分辨率的Gloucester数据集了吗，是否介意分享给我，非常感谢。邮箱地址：202383060075@sdust.edu.cn

**Comment by yulisun** [comment]
抱歉，126的邮箱应该是被拒收了，数据集相关信息已发送邮箱，请查收。

**Comment by zhuangyong6666-dot** [comment]
> 抱歉，126的邮箱应该是被拒收了，数据集相关信息已发送邮箱，请查收。

您好，我是计算机研究生，现在的研究方向涉及异源图像变化检测，是否介意分享给我，非常感谢。邮箱地址：942662468
@qq.com

**Comment by XDW-2025** [comment]
> 您好，github上的数据是下采样过了的，原始4135×2325图像有80多M，不便于github上传。如果方便的话请邮件联系，我需要知道您使用这个数据集是用于研究或是其他用途。

老师您好，我是遥感院的在读研究生，现在的课题与异构图像变化检测有关，高分辨率的Gloucester数据集对我的研究有帮助，但是目前没有找到下载渠道，在这里向您咨询，您是否介意将Gloucester数据集数据集分享给我，我的邮箱是xerenelull@qq.com，非常期待您的回复！
